# Generated by Django 4.2 on 2023-04-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Listas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
        migrations.AddField(
            model_name='iten',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='Listas.lista'),
        ),
    ]
