# Generated by Django 4.2 on 2023-04-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listas', '0003_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
