# Generated by Django 4.2 on 2023-04-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listas', '0005_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='last',
        ),
    ]
